export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SERVICE_TIMEOUT: 'SERVICE_TIMEOUT',
  SERVICE_UNREACHABLE: 'SERVICE_UNREACHABLE',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export const EARTH_RADIUS_METERS = 6_371_000;

export const DEFAULT_PAGE_SIZE = 10;

export const MAX_PAGE_SIZE = 100;
