name: Deploy Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Hanya berjalan jika pesan commit mengandung teks spesifik
    if: contains(github.event.head_commit.message, ':rocket: CI Deploy: Update Version')
    
    steps:
      - name: Execute Deployment Script via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # Port opsional, default 22 jika tidak diatur
          port: ${{ secrets.VPS_PORT || '22' }}
          script: |
            echo "Starting Deployment Process..."
            cd /home/bintang/pa-be
            
            echo "Pulling latest code from main..."
            git pull origin main
            
            echo "Installing dependencies..."
            npm install
            
            echo "Building packages..."
            npm run build
            
            echo "Restarting Systemd services..."
            sudo systemctl restart fintap-gateway fintap-auth fintap-attendance fintap-activity fintap-request fintap-config fintap-notification
            
            echo "Deployment Completed Successfully!"
